### ISSUE TITLE
nasbench sampling procedure

### ISSUE THREAD

**Issue by fmsnew** [naszilla/bananas#1]
Is sampling of nasbench architectures valid in **generate_random_dataset** and **random_cell** methods?

I've tried to sample uniform hashes and got much worse test errors (see this 
[notebook](https://github.com/fmsnew/bananas/blob/master/meta_neuralnet-reproduce.ipynb) )

Perhaps generation of random architectures until they are valid makes the sample biased towards more predictable architectures.

Also, how do you ensure that train and test samples do not intersect?

**Comment by crwhite14** [comment]
Hi, the sampling procedure we used, `random_cell()` in `bananas/nas_bench/cell.py`, is directly from the experiments of the original NASbench paper. In general, this non-uniform sampling procedure is valid for NAS algorithms to utilize, and you could argue it is much simpler than uniform sampling. For example, the DARTS search space contains 10^14 architectures, so we cannot enumerate them all at once.

Your notebook shows that sampling uniformly at random does not perform as well as the `random_cell()` method. We suspect that this is because uniform sampling gives a higher weight to architectures with long, unique paths which are less likely to occur in other neural networks, making it hard for the meta neural network to generalize. 

Thanks, we updated the notebook to ensure train and test samples do not intersect (results are affected by under 0.1%).
